GET http://localhost:8082

###
# @name GetIOSCode
# POST request for iOS code, matching the server's validation schema
###
# @name GetIOSCode
# POST request for iOS code, matching the server's validation schema
POST http://localhost:8082/get-ios-code
Content-Type: application/json

{ 
    "input":{
         "code": "c5ea41a37797b438dafe32265f8872a4b.0.pwtu.CrQGKYg0_QwBysrpvkK0Ug",
        "redirectTo": "https://staging-fe.kofuku.com/callback/apple"
    }
}

###
# @name GetIOSCode
# POST request for iOS code, matching the server's validation schema
POST http://localhost:8082/login-ios
Content-Type: application/json

{ 
    "input":{
        "redirectTo": "https://staging-fe.kofuku.com/callback/apple"
    }
}



###
# @name GetGoogleCode
#  it is working 
POST http://localhost:8082/login-ios
Content-Type: application/json

{ 
    "input":{
        "redirectTo": "https://auth-test-next-app-tapasxkofukus-projects.vercel.app/api/auth/callback/apple"
    }
}

###
# @name GetGoogleCode
#  it is working 
POST http://localhost:8082/login-ios
Content-Type: application/json

{ 
    "input":{
        "redirectTo": "https://staging-fe.kofuku.com/callback/apple"
    }
}
